name: Build SimplePaintball

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Set up JDK 21
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21.0.9
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package
      - name: Upload plugin
        uses: actions/upload-artifact@v6.0.0
        with:
          name: SimplePaintball
          path: target/SimplePaintball-*.jar